### ISSUE TITLE
ExtendedNestedScrollView on collapse

### ISSUE THREAD

**Issue by niegus** [fluttercandies/Flutter_Candies#1]
How can I know when the sliver App bar is collapsed with your ExtendedNestedScrollView?

Thanks!

**Comment by zmtzawqlp** [comment]
why do you want to konw, the code is in sliver app bar, may be you can see it in https://gist.github.com/zmtzawqlp/63a475bb825ae76b8c8c8cb7cfb9b5b5  , it's a simple sliver app bar

**Comment by niegus** [comment]
As long as I know there is no method in SliverAppBar, the way I used to do this was setting a scrollController in the NestedScrollView and then with:

return _scrollController.hasClients
        && _scrollController.offset > kExpandedHeight - kToolbarHeight;

I've tried this with the ExtendedNestedScrollView and doesn't work.

**Comment by zmtzawqlp** [comment]
I'm sorry, i still not understand your case, may be tell me what effect do you want to build, it will better to me.  gif 
and ExtendedNestedScrollView slove two issues , i don't konw whether it's done for your case.

**Comment by firecolen** [comment]
if I use StaggeredGridView,tabbar can not scroll to top

**Comment by zmtzawqlp** [comment]
it seems you have no problem yet, re-open if you have other issue
