### ISSUE TITLE
type 'Future<void>' is not a subtype of type 'Future<Null>' when keyboard shown

### ISSUE THREAD

**Issue by apps-transround** [fluttercandies/Flutter_Candies#2]
Having a text input widget in a staggered grid that needs to scroll up when soft keyboard appears: 

Caught error: type 'Future\<void>' is not a subtype of type 'Future\<Null>'
I/flutter (14094): #0      _NestedScrollCoordinator.animateTo (package:extended_nested_scroll_view/src/old_extended_nested_scroll_view.dart:774:75)
I/flutter (14094): \<asynchronous suspension>
I/flutter (14094): #1      _NestedScrollPosition.animateTo (package:extended_nested_scroll_view/src/old_extended_nested_scroll_view.dart:1281:24)

**Comment by zmtzawqlp** [comment]
please give mode code, and the error case.  it seems staggered grid is not widget from flutter team

**Comment by apps-transround** [comment]
There is no need to reproduce, just check the code:

pub.dartlang.org/extended_nested_scroll_view-0.2.9/lib/src/old_extended_nested_scroll_view.dart:774

  final List\<Future\<Null>> resultFutures = \<Future\<Null>>[outerActivity.done];

get done → Future\<void>   not \<Future\<Null>>

**Comment by zmtzawqlp** [comment]
suggest use flutter official nestedscrollview to check whether it is your staggered grid has some error,  staggered grid seems like an un-official  widget. i can't debug without your case code. extended_nested_scroll_view's code are all from official nestedscrollview ,it just fix two cases issues

**Comment by apps-transround** [comment]
I've checked the official nested scroll view. The bug is already corrected there. 
packages/flutter/lib/src/widgets/nested_scroll_view.dart:725

Please update your version, thanks.

**Comment by zmtzawqlp** [comment]
0.3.0 is already, please check whether it fix your issue

**Comment by apps-transround** [comment]
Working, thanks.
