### ISSUE TITLE
法佬，请问怎么将自己项目加入flutter_candies?

### ISSUE THREAD

**Issue by CNAD666** [fluttercandies/flutter_candies#4]
法佬，请问怎么将自己开源的项目加入flutter_candies? 

关于flutter自带dialog存在一些痛点，对于这些痛点我做了一个解决方案，写了一个开源库，请问怎么能加入flutter_candies，有什么要求：https://github.com/CNAD666/flutter_smart_dialog

**Comment by zmtzawqlp** [comment]
看看你的项目呢

**Comment by CNAD666** [comment]
> 看看你的项目呢

大佬，你看看哈：https://github.com/CNAD666/flutter_smart_dialog

**Comment by zmtzawqlp** [comment]
发邮件给你了。然后你加入之后。把项目transform 到组织就好了

**Comment by CNAD666** [comment]
> 发邮件给你了。然后你加入之后。把项目transform 到组织就好了

嗯嗯，好的ヽ(￣▽￣)و

**Comment by zmtzawqlp** [comment]
commit 还是养成写英文好点

**Comment by CNAD666** [comment]
> commit 还是养成写英文好点

哈哈，好的，下次一定

**Comment by CNAD666** [comment]
搞定了
