### ISSUE TITLE
Does it work with long lists?

### ISSUE THREAD

**Issue by JoonDong2** [fluttercandies/flutter_candies#7]
I have a question before using it.
Does it work with long lists?
Thank you.

**Comment by zmtzawqlp** [comment]
?? which widget do you use?

**Comment by JoonDong2** [comment]
> ?? which widget do you use?

Sorry, I meant the waterfall widget.

**Comment by zmtzawqlp** [comment]
yes, of course

**Comment by JoonDong2** [comment]
> yes, of course

Thank you.
